FROM golang:1.19-buster AS builder
MAINTAINER Hector Sanjuan <hector@protocol.ai>

# This dockerfile builds cluster and runs it along with go-ipfs.
# It re-uses the latest go-ipfs:release container.

# This builder just builds the cluster binaries
ENV GOPATH      /go
ENV SRC_PATH    $GOPATH/src/github.com/mtdepin/rep-mgr
ENV GO111MODULE on
ENV GOPROXY     https://proxy.golang.org

COPY --chown=1000:users go.* $SRC_PATH/
WORKDIR $SRC_PATH
RUN go mod download

COPY --chown=1000:users . $SRC_PATH
RUN make install

#------------------------------------------------------
FROM ipfs/go-ipfs:release
MAINTAINER Hector Sanjuan <hector@protocol.ai>

# This is the container which just puts the previously
# built binaries on the go-ipfs-container.

ENV GOPATH                 /go
ENV SRC_PATH               /go/src/github.com/mtdepin/rep-mgr
ENV IPFS_CLUSTER_PATH      /data/rep-mgr
ENV IPFS_CLUSTER_CONSENSUS crdt
ENV IPFS_CLUSTER_DATASTORE leveldb

EXPOSE 9094
EXPOSE 9095
EXPOSE 9096

COPY --from=builder $GOPATH/bin/rep-mgr-service /usr/local/bin/rep-mgr-service
COPY --from=builder $GOPATH/bin/rep-mgr-ctl /usr/local/bin/rep-mgr-ctl
COPY --from=builder $GOPATH/bin/rep-mgr-follow /usr/local/bin/rep-mgr-follow
COPY --from=builder $SRC_PATH/docker/start-daemons.sh /usr/local/bin/start-daemons.sh

RUN mkdir -p $IPFS_CLUSTER_PATH && \
    chown 1000:100 $IPFS_CLUSTER_PATH

VOLUME $IPFS_CLUSTER_PATH
ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/start-daemons.sh"]

# Defaults for rep-mgr-service go here
CMD ["daemon"]
